import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { Layouts } from "../widgets/layouts";
import localFont from 'next/font/local'
import { StoreProvider } from "../redux/provider";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <Layouts>

          {children}
        </Layouts>


      </body>
    </html>

  );
}
